---
title: "P8105 HW6"
output: github_document
date: "2024-11-29"
---


```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(purrr)
library(modelr)
library(broom)
```

# Problem 1 

Setting Up 
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Creating the Function first. 
```{r}
boot_fun = function(df) {
  boot_samp = modelr::bootstrap(df, 1)
  
  boot_data = boot_samp[[1]]
  
  lm_fit = lm(tmax ~ tmin, data = boot_data)
  
  glance_out = broom::glance(lm_fit)
  tidy_out = broom::tidy(lm_fit)
  
  return(tibble(
    r_squared = glance_out[['r.squared']], 
    log_est = log(tidy_out[['estimate']][1] * tidy_out[['estimate']][2])  
  ))
}
```

5000 Bootstrap Samples. 
```{r}
boot_straps = 
  weather_df %>%
  modelr::bootstrap(n = 5000)
```

```{r}
boot_results = 
  boot_straps %>% 
  mutate(
    results = map(strap, function(boot_samp) {
      lm_fit = lm(tmax ~ tmin, data = boot_samp)
      
      glance_out = broom::glance(lm_fit)
      tidy_out = broom::tidy(lm_fit)
      
      return(tibble(
        r_squared = glance_out[['r.squared']], 
        log_est = log(tidy_out[['estimate']][1] * tidy_out[['estimate']][2])  
      ))
    })) %>% 
  unnest(results) 
```

Histogram: R Squared 
```{r}
boot_results %>%
  ggplot(aes(x = r_squared)) +
  geom_histogram(binwidth = 0.001, fill = "lightblue", color = "black") +
  labs(title = "Distribution of R-squared from Bootstrap Samples",
       x = "R-squared", y = "Frequency")
```

Histogram: Log 
```{r}
boot_results %>%
  ggplot(aes(x = log_est)) +
  geom_histogram(binwidth = 0.02, fill = "lightgreen", color = "black") +
  labs(title = "Distribution of log(beta0 * beta1) from Bootstrap Samples",
       x = "log(beta0 * beta1)", y = "Frequency")
```

# Problem 2 

```{r}
homicide_df = read_csv("data/homicide-data.csv")

homicide_df = homicide_df %>%
  mutate(city_state = paste(city, state, sep = ", ")) %>% 
  filter(city_state != "Dallas, TX",
         city_state != "Phoenix, AZ",
         city_state != "Kansas City, MO",
         city_state != "Tulsa, AL",
         victim_race == "White" | victim_race == "Black") %>% 
  mutate(
    resolved = as.numeric(disposition == "Closed by arrest"),
    victim_age = as.numeric(victim_age)
  ) 
```

Regression Model and CI Calculations 
```{r}
baltimore_model = 
  homicide_df %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(resolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial())

baltimore_model %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate),  
         conf.low = exp(estimate - 1.96 * std.error), 
         conf.high = exp(estimate + 1.96 * std.error)) %>%  
  filter(term == "victim_sexMale") %>%  
  select(term, OR, conf.low, conf.high) 
```

```{r}
city_model_results = homicide_df %>% 
  nest(data = -city_state) %>%  
  mutate(
    models = map(data, ~ glm(resolved ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())),  
    results = map(models, broom::tidy)  
  ) %>% 
  select(-data, -models) %>%  
  unnest(results) %>% 
  mutate(
    OR = exp(estimate), 
    conf.low = exp(estimate - 1.96 * std.error),  
    conf.high = exp(estimate + 1.96 * std.error) 
  ) %>% 
  filter(term == "victim_sexMale") %>%  
  select(city_state, term, OR, conf.low, conf.high)  
```

Plotting the Results 
```{r}
city_model_results %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  coord_flip() +
  labs(title = "Odds Ratios for Solving Homicides (Male vs. Female)", 
       x = "City, State", 
       y = "Odds Ratio")
```

